sudo: required
language: java
jdk:
- oraclejdk8
before_install:
- curl -sL http://bit.ly/jpm4j >jpm4j.jar
- sudo java -jar jpm4j.jar -g init
- sudo jpm install com.codacy:codacy-coverage-reporter:assembly
before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
after_success:
- codacy-coverage-reporter -l Java -r build/reports/jacoco/test/jacocoTestReport.xml  --prefix src/main/java/
deploy:
  provider: heroku
  api_key:
    secure: EkfNZXn6RHrpz8LNvv10FiOBEUwNs8wqh2kEmFaS1ADSmehH5Azo446Y/zBdqgPXHrz4beV6U3Vx5zIfxixJQOx5XHklTC6nEZ5yH+wUZM16jGgcVvvlZOXS6TegDVCWjtn5SLt/SoPq2gRbEWDX/4+S1uadPhWzoWRvn1NI0V/tYkZxRjneUcpEWJQk0XgXW/GHly7LSXnwWuIqnyRAPK2JrTBom9hHO3pOe9ThbCxr6cDwh6N+rmwlKlgCgFdiE843pdbB0nCl/o46/RNXSTEJH9KTG+PuZRKicpxpApalo4QQfb3mFDvqsbxZZlTgTpuzwVYnNuC0+cxrMxMJAJcV2aZ0erGVrfgYXU+YQbbu08PXbhLq5tEE9DT/Zr0y3oWCCp80MVAF6BT+4Cn0txoc+fpWRY/bwWMS7SXv0fIepJnoq9P6KlpWjXQJZmFZP79J24kxy7qgGXg78obh4+Bp1S+rqDQvjTMQawzK+TCVoU6g0qWI5iNlwts1gR30mCf0hpiSSoGKnAsBaG/cGKNww+aCzFLiT6NtA8gV+i+LqpgHb4Ipm8vuNau4VM9dlKVQ4FCbXX2tlgRlqtJuHdcawrGB9sy0+6uvOgy/BqC6mEcQF9mu3jVompgeVRzAhfl5g2DSuDEquHFroQApwSovJZlpv991bDUmTxyzRVI=
  app: hello-world-java-blogcs
  on:
    repo: joao-felipe-cs/hello-world-java
